version: '0.1.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

configuration: Release

before_build:
 - nuget restore
