version: '0.1.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

configuration: Release

before_build:
 - nuget restore
 
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

deploy:
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: NiEHpwU2P6o26pf83cJDf+tqPQAJNdOP8PrXvMfQrIQHRbI0uk48aftgyfIqh1mh
    artifact: /.*\.nupkg/
